config/routes.rb
Rails.application.routes.draw do

  root "pages#hello"

  get "/about", to: "pages#about"
  get "/help", to: "pages#help"

  resources :todos
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
  validates :name, presence: true
  validates :description, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def hello
  end

  def about
  end

  def help
  end

end

app/controllers/todos_controller.rb
class TodosController < ApplicationController

  before_action :initialize_todo, only: [:show, :edit, :update, :destroy]

  def new
    @todo = Todo.new()
  end

  def create
    @todo = Todo.new(todo_params)
    if @todo.save
      # Save message to flash for later use in view
      flash[:notice] = "Todo was successfully saved !"

      redirect_to todo_path(@todo)
    else
      render 'new'
    end
  end

  def show
  end

  def edit
  end

  def update
    if @todo.update(todo_params)
      # Save message to flash for later use in view
      flash[:notice] = "Todo was successfully updated !"

      redirect_to todo_path(@todo)
    else
      render 'edit'
    end
  end

  def destroy
    if @todo.destroy
      flash[:notice] = "Todo was successfully deleted !"
      redirect_to todos_path
    end
  end

  def index
    @todos = Todo.all
  end

  private
    def todo_params
      params.require(:todo).permit(:name, :description)
    end

    def initialize_todo
      @todo = Todo.find(params[:id])
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_messages.html.erb
<ul>
  <% flash.each do |name, msg| %>
    <li><%= msg %></li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todoapp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/messages' %>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1> This is an about page ! </h1>

app/views/pages/hello.html.erb
<h1>Hello World !</h1>
<h2>This is my amazing test :)</h2>
<h3>This is homepage</h3>

app/views/pages/help.html.erb
<h1>This is help page</h1>

app/views/todos/_form.html.erb
<% if @todo.errors.any? %>
  <h2>Error:<h2>
  <ul>
    <% @todo.errors.full_messages.each do |msg|%>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for @todo do |f| %>
  <p>
    <%= f.label :name %> <br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :description %> <br>
    <%= f.text_area :description %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to "Back to listing", todos_path %>

app/views/todos/edit.html.erb
<h1>Edit todo.</h1>
<%= render 'form' %>

app/views/todos/index.html.erb
<h1>Todos listing</h1>

<%= link_to "Create new todo", new_todo_path %>
<br>
<br>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
  <tr>
  <% @todos.each do |todo| %>
    <tr>
      <td> <%= todo.name %> </td>
      <td> <%= todo.description %> </td>
      <td> <%= link_to "Show", todo_path(todo) %> </td>
      <td> <%= link_to "Edit", edit_todo_path(todo) %> </td>
      <td> <%= link_to "Delete", todo_path(todo), method: :delete %> </td>
    <tr>
  <% end %>
</table>

app/views/todos/new.html.erb
<h1>Create new Todos !</h1>
<%= render 'form' %>

app/views/todos/show.html.erb
<h1>Showing a todo !</h1>
  Name: <%= @todo.name %> <br>
  Description: <%= @todo.description %>
<br>

<%= link_to "Back to listing", todos_path %> |
<%= link_to "Edit", edit_todo_path(@todo) %>